package simulationManager.simulation.items;

import simulationManager.simulation.Item;

import java.util.ArrayList;

public class ItemList {
    public static AbyssalMask abyssalMask = new AbyssalMask();
    public static AegisOfTheLegion aegisOfTheLegion = new AegisOfTheLegion();
    public static AetherWisp aetherWisp = new AetherWisp();
    public static AmplifyingTome amplifyingTome = new AmplifyingTome();
    public static AnathemasChains anathemasChains = new AnathemasChains();
    public static AxiomArc axiomArc = new AxiomArc();
    public static BamisCinder bamisCinder = new BamisCinder();
    public static BandleglassMirror bandleglassMirror = new BandleglassMirror();
    public static BansheesVeil bansheesVeil = new BansheesVeil();
    public static BerserkersGreaves berserkersGreaves = new BerserkersGreaves();
    public static BFSword bFSword = new BFSword();
    public static BlackCleaver blackCleaver = new BlackCleaver();
    public static BlackMistScythe blackMistScythe = new BlackMistScythe();
    public static BladeOfTheRuinedKing bladeOfTheRuinedKing = new BladeOfTheRuinedKing();
    public static BlastingWand blastingWand = new BlastingWand();
    public static BlightingJewel blightingJewel = new BlightingJewel();
    public static Bloodthister bloodthister = new Bloodthister();
    public static BrambleVest brambleVest = new BrambleVest();
    public static BulwackOfTheMountain bulwackOfTheMountain = new BulwackOfTheMountain();
    public static CatalystOfAeons catalystOfAeons = new CatalystOfAeons();
    public static CaulfieldsWarhammer caulfieldsWarhammer = new CaulfieldsWarhammer();
    public static ChainVest chainVest = new ChainVest();
    public static ChempunkChainsword chempunkChainsword = new ChempunkChainsword();
    public static CloakOfAgility cloakOfAgility = new CloakOfAgility();
    public static ClothArmor clothArmor = new ClothArmor();
    public static CosmicDrive cosmicDrive = new CosmicDrive();
    public static CrownOfTheShatteredQueen crownOfTheShatteredQueen = new CrownOfTheShatteredQueen();
    public static CrystallineBracer crystallineBracer = new CrystallineBracer();
    public static Cull cull = new Cull();
    public static Dagger dagger = new Dagger();
    public static DarkSeal darkSeal = new DarkSeal(0);
    public static DeathsDance deathsDance = new DeathsDance();
    public static DemonicEmbrace demonicEmbrace = new DemonicEmbrace();
    public static DivineSunderer divineSunderer = new DivineSunderer();
    public static DoransBlade doransBlade = new DoransBlade();
    public static DoransRing doransRing = new DoransRing();
    public static DoransShield doransShield = new DoransShield();
    public static DuskbladeOfDraktharr duskbladeOfDraktharr = new DuskbladeOfDraktharr();
    public static Eclipse eclipse = new Eclipse();
    public static EdgeOfNight edgeOfNight = new EdgeOfNight();
    public static EssenceReaver essenceReaver = new EssenceReaver();
    public static Evenshroud evenshroud = new Evenshroud();
    public static Everfrost everfrost = new Everfrost();
    public static ExecutionersCalling executionersCalling = new ExecutionersCalling();
    public static FaerieCharm faerieCharm = new FaerieCharm();
    public static FiendishCodex fiendishCodex = new FiendishCodex();
    public static Fimbulwinter fimbulwinter = new Fimbulwinter();
    public static ForbiddenIdol forbiddenIdol = new ForbiddenIdol();
    public static Frostfang frostfang = new Frostfang();
    public static FrozenHeart frozenHeart = new FrozenHeart();
    public static Galeforce galeforce = new Galeforce();
    public static GiantsBelt giantsBelt = new GiantsBelt();
    public static GlacialBuckler glacialBuckler = new GlacialBuckler();
    public static Goredrinker goredrinker = new Goredrinker();
    public static GuardianAngel guardianAngel = new GuardianAngel();
    public static GuardiansBlade guardiansBlade = new GuardiansBlade();
    public static GuardiansHammer guardiansHammer = new GuardiansHammer();
    public static GuardiansHorn guardiansHorn = new GuardiansHorn();
    public static GuardiansOrb guardiansOrb = new GuardiansOrb();
    public static GuinsoosRageblade guinsoosRageblade = new GuinsoosRageblade();
    public static HarrowingCrescent harrowingCrescent = new HarrowingCrescent();
    public static HearthboundAxe hearthboundAxe = new HearthboundAxe();
    public static Heartsteel heartsteel = new Heartsteel();
    public static Hexdrinker hexdrinker = new Hexdrinker();
    public static HextechAlternator hextechAlternator = new HextechAlternator();
    public static HextechRocketbelt hextechRocketbelt = new HextechRocketbelt();
    public static HorizonFocus horizonFocus = new HorizonFocus();
    public static Hullbreaker hullbreaker = new Hullbreaker();
    public static IcebornGauntlet icebornGauntlet = new IcebornGauntlet();
    public static ImmortalShieldbow immortalShieldbow = new ImmortalShieldbow();
    public static ImperialMandate imperialMandate = new ImperialMandate();
    public static InfinityEdge infinityEdge = new InfinityEdge();
    public static IonianBootsOfLucidity ionianBootsOfLucidity = new IonianBootsOfLucidity();
    public static IronspikeWhip ironspikeWhip = new IronspikeWhip();
    public static JakSho jakSho = new JakSho();
    public static Kindlegem kindlegem = new Kindlegem();
    public static KircheisShard kircheisShard = new KircheisShard();
    public static KrakenSlayer krakenSlayer = new KrakenSlayer();
    public static LastWhisper lastWhisper = new LastWhisper();
    public static LeechingLeer leechingLeer = new LeechingLeer();
    public static LiandrysAnguish liandrysAnguish = new LiandrysAnguish();
    public static LichBane lichBane = new LichBane();
    public static LocketOfTheIronSolari locketOfTheIronSolari = new LocketOfTheIronSolari();
    public static LongSword longSword = new LongSword();
    public static LordDominiksRegards lordDominiksRegards = new LordDominiksRegards();
    public static LostChapter lostChapter = new LostChapter();
    public static LudensTempest ludensTempest = new LudensTempest();
    public static MawOfMalmortius mawOfMalmortius = new MawOfMalmortius();
    public static MejaisSoulstealer mejaisSoulstealer = new MejaisSoulstealer(0);
    public static MercurialScimitar mercurialScimitar = new MercurialScimitar();
    public static MoonstoneRenewer moonstoneRenewer = new MoonstoneRenewer();
    public static Morellonomicon morellonomicon = new Morellonomicon();
    public static MortalReminder mortalReminder = new MortalReminder();
    public static Muramana muramana = new Muramana();
    public static NashorsTooth nashorsTooth = new NashorsTooth();
    public static NavoriQuickblades navoriQuickblades = new NavoriQuickblades();
    public static NeedlesslyLargeRod needlesslyLargeRod = new NeedlesslyLargeRod();
    public static NegatronCloak negatronCloak = new NegatronCloak();
    public static NightHarvester nightHarvester = new NightHarvester();
    public static Noonquiver noonquiver = new Noonquiver();
    public static NullMagicMantle nullMagicMantle = new NullMagicMantle();
    public static OblivionOrb oblivionOrb = new OblivionOrb();
    public static PauldronsOfWhiterock pauldronsOfWhiterock = new PauldronsOfWhiterock();
    public static Phage phage = new Phage();
    public static PhantomDancer phantomDancer = new PhantomDancer();
    public static Pickaxe pickaxe = new Pickaxe();
    public static ProwlersClaw prowlersClaw = new ProwlersClaw(true);
    public static QuicksilverSash quicksilverSash = new QuicksilverSash();
    public static RabbadonsDeathcap rabbadonsDeathcap = new RabbadonsDeathcap();
    public static RadiantVirtue radiantVirtue = new RadiantVirtue();
    public static Rageknife rageknife = new Rageknife();
    public static RanduinsOmen randuinsOmen = new RanduinsOmen();
    public static RapidFirecannon rapidFirecannon = new RapidFirecannon();
    public static RavenousHydra ravenousHydra = new RavenousHydra(0);
    public static RecurveBow recurveBow = new RecurveBow();
    public static RejuvenationBead rejuvenationBead = new RejuvenationBead();
    public static RelicShield relicShield = new RelicShield();
    public static Riftmaker riftmaker = new Riftmaker();
    public static RodOfAges rodOfAges = new RodOfAges();
    public static RubyCrystal rubyCrystal = new RubyCrystal();
    public static RunaansHurrycane runaansHurrycane = new RunaansHurrycane();
    public static RunesteelSpaulders runesteelSpaulders = new RunesteelSpaulders();
    public static RylaisCrystalScepter rylaisCrystalScepter = new RylaisCrystalScepter();
    public static SapphireCrystal sapphireCrystal = new SapphireCrystal();
    public static SeekersArmguard seekersArmguard = new SeekersArmguard(0);
    public static SeraphsEmbrace seraphsEmbrace = new SeraphsEmbrace();
    public static SerpentsFang serpentsFang = new SerpentsFang();
    public static SerratedDirk serratedDirk = new SerratedDirk();
    public static SeryldasGrudge seryldasGrudge = new SeryldasGrudge();
    public static Shadowflame shadowflame = new Shadowflame();
    public static ShardOfTrueIce shardOfTrueIce = new ShardOfTrueIce();
    public static Sheen sheen = new Sheen();
    public static ShureliasBattlesong shureliasBattlesong = new ShureliasBattlesong();
    public static SilvermereDawn silvermereDawn = new SilvermereDawn();
    public static SorcerersShoes sorcerersShoes = new SorcerersShoes();
    public static SpearOfShojin spearOfShojin = new SpearOfShojin();
    public static SpectralSickle spectralSickle = new SpectralSickle();
    public static SpectresCowl spectresCowl = new SpectresCowl();
    public static SpellthiefsEdge spellthiefsEdge = new SpellthiefsEdge();
    public static SteelShoulderguards steelShoulderguards = new SteelShoulderguards();
    public static SteraksCage steraksCage = new SteraksCage();
    public static Stormrazor stormrazor = new Stormrazor();
    public static Stridebreaker stridebreaker = new Stridebreaker();
    public static SunfireAegis sunfireAegis = new SunfireAegis();
    public static TargonsBuckler targonsBuckler = new TargonsBuckler();
    public static TearOfTheGoddess tearOfTheGoddess = new TearOfTheGoddess(0);
    public static TheCollector theCollector = new TheCollector();
    public static Tiamat tiamat = new Tiamat();
    public static TitanicHydra titanicHydra = new TitanicHydra();
    public static TrinityForce trinityForce = new TrinityForce();
    public static UmbralGlaive umbralGlaive = new UmbralGlaive();
    public static VampiricScepter vampiricScepter = new VampiricScepter();
    public static VerdantBarrier verdantBarrier = new VerdantBarrier(0);
    public static VigilantWardstone vigilantWardstone = new VigilantWardstone();
    public static VoidStaff voidStaff = new VoidStaff();
    public static WardensMail wardensMail = new WardensMail();
    public static WarmongsArmor warmongsArmor = new WarmongsArmor();
    public static WatchfulWardstone watchfulWardstone = new WatchfulWardstone();
    public static WingedMoonplate wingedMoonplate = new WingedMoonplate();
    public static WitsEnd witsEnd = new WitsEnd();
    public static YoummuusGhostblade yoummuusGhostblade = new YoummuusGhostblade();
    public static Zeal zeal = new Zeal();
    public static ZhonyasHourglass zhonyasHourglass = new ZhonyasHourglass();


    public static ArrayList<Item> allItems = new ArrayList<>() {{
        add(abyssalMask);
        add(aegisOfTheLegion);
        add(aetherWisp);
        add(amplifyingTome);
        add(anathemasChains);
        add(axiomArc);
        add(bamisCinder);
        add(bandleglassMirror);
        add(bansheesVeil);
        add(berserkersGreaves);
        add(bFSword);
        add(blackCleaver);
        add(blackMistScythe);
        add(bladeOfTheRuinedKing);
        add(blastingWand);
        add(blightingJewel);
        add(bloodthister);
        add(brambleVest);
        add(bulwackOfTheMountain);
        add(catalystOfAeons);
        add(caulfieldsWarhammer);
        add(chainVest);
        add(chempunkChainsword);
        add(cloakOfAgility);
        add(clothArmor);
        add(cosmicDrive);
        add(crownOfTheShatteredQueen);
        add(crystallineBracer);
        add(cull);
        add(dagger);
        add(darkSeal);
        add(deathsDance);
        add(demonicEmbrace);
        add(divineSunderer);
        add(doransBlade);
        add(doransRing);
        add(doransShield);
        add(duskbladeOfDraktharr);
        add(eclipse);
        add(edgeOfNight);
        add(essenceReaver);
        add(evenshroud);
        add(everfrost);
        add(executionersCalling);
        add(faerieCharm);
        add(fiendishCodex);
        add(fimbulwinter);
        add(forbiddenIdol);
        add(frostfang);
        add(frozenHeart);
        add(galeforce);
        add(giantsBelt);
        add(glacialBuckler);
        add(goredrinker);
        add(guardianAngel);
        add(guardiansBlade);
        add(guardiansHammer);
        add(guardiansHorn);
        add(guardiansOrb);
        add(guinsoosRageblade);
        add(harrowingCrescent);
        add(hearthboundAxe);
        add(heartsteel);
        add(hexdrinker);
        add(hextechAlternator);
        add(hextechRocketbelt);
        add(horizonFocus);
        add(hullbreaker);
        add(icebornGauntlet);
        add(immortalShieldbow);
        add(imperialMandate);
        add(infinityEdge);
        add(ionianBootsOfLucidity);
        add(ironspikeWhip);
        add(jakSho);
        add(kindlegem);
        add(kircheisShard);
        add(krakenSlayer);
        add(lastWhisper);
        add(leechingLeer);
        add(liandrysAnguish);
        add(lichBane);
        add(locketOfTheIronSolari);
        add(longSword);
        add(lordDominiksRegards);
        add(lostChapter);
        add(ludensTempest);
        add(mawOfMalmortius);
        add(mejaisSoulstealer);
        add(mercurialScimitar);
        add(moonstoneRenewer);
        add(morellonomicon);
        add(mortalReminder);
        add(muramana);
        add(nashorsTooth);
        add(navoriQuickblades);
        add(needlesslyLargeRod);
        add(negatronCloak);
        add(nightHarvester);
        add(noonquiver);
        add(nullMagicMantle);
        add(oblivionOrb);
        add(pauldronsOfWhiterock);
        add(phage);
        add(phantomDancer);
        add(pickaxe);
        add(prowlersClaw);
        add(quicksilverSash);
        add(rabbadonsDeathcap);
        add(radiantVirtue);
        add(rageknife);
        add(randuinsOmen);
        add(rapidFirecannon);
        add(ravenousHydra);
        add(recurveBow);
        add(rejuvenationBead);
        add(relicShield);
        add(riftmaker);
        add(rodOfAges);
        add(rubyCrystal);
        add(runaansHurrycane);
        add(runesteelSpaulders);
        add(rylaisCrystalScepter);
        add(sapphireCrystal);
        add(seekersArmguard);
        add(seraphsEmbrace);
        add(serpentsFang);
        add(serratedDirk);
        add(seryldasGrudge);
        add(shadowflame);
        add(shardOfTrueIce);
        add(sheen);
        add(shureliasBattlesong);
        add(silvermereDawn);
        add(sorcerersShoes);
        add(spearOfShojin);
        add(spectralSickle);
        add(spectresCowl);
        add(spellthiefsEdge);
        add(steelShoulderguards);
        add(steraksCage);
        add(stormrazor);
        add(stridebreaker);
        add(sunfireAegis);
        add(targonsBuckler);
        add(tearOfTheGoddess);
        add(theCollector);
        add(tiamat);
        add(titanicHydra);
        add(trinityForce);
        add(umbralGlaive);
        add(vampiricScepter);
        add(verdantBarrier);
        add(vigilantWardstone);
        add(voidStaff);
        add(wardensMail);
        add(warmongsArmor);
        add(watchfulWardstone);
        add(wingedMoonplate);
        add(witsEnd);
        add(yoummuusGhostblade);
        add(zeal);
        add(zhonyasHourglass);
    }};

    public static ArrayList<Item> allMagicDmg = new ArrayList<>() {{
        add(aetherWisp);
        add(amplifyingTome);
        add(bandleglassMirror);
        add(bansheesVeil);
        add(blastingWand);
        add(blightingJewel);
        add(cosmicDrive);
        add(crownOfTheShatteredQueen);
        add(darkSeal);
        add(demonicEmbrace);
        add(doransRing);
        add(everfrost);
        add(fiendishCodex);
        add(hextechAlternator);
        add(hextechRocketbelt);
        add(horizonFocus);
        add(imperialMandate);
        add(leechingLeer);
        add(liandrysAnguish);
        add(lichBane);
        add(lostChapter);
        add(ludensTempest);
        add(mejaisSoulstealer);
        add(moonstoneRenewer);
        add(morellonomicon);
        add(nashorsTooth);
        add(needlesslyLargeRod);
        add(nightHarvester);
        add(oblivionOrb);
        add(rabbadonsDeathcap);
        add(riftmaker);
        add(rodOfAges);
        add(rylaisCrystalScepter);
        add(seekersArmguard);
        add(seraphsEmbrace);
        add(shadowflame);
        add(shureliasBattlesong);
        add(verdantBarrier);
        add(voidStaff);
        add(zhonyasHourglass);

        add(sorcerersShoes);
        add(abyssalMask);
    }};
}
