package com.damagecalculator.simulationManager.simulation.items;

import com.damagecalculator.simulationManager.simulation.Item;

import java.util.ArrayList;
import java.util.HashMap;

public class ItemList {
    public static AbyssalMask abyssalMask = new AbyssalMask();
    public static AegisOfTheLegion aegisOfTheLegion = new AegisOfTheLegion();
    public static AetherWisp aetherWisp = new AetherWisp();
    public static AmplifyingTome amplifyingTome = new AmplifyingTome();
    public static ArchangelsStaff archangelsStaff = new ArchangelsStaff(0);
    public static ArdentCenser ardentCenser = new ArdentCenser();
    public static AxiomArc axiomArc = new AxiomArc();
    public static BamisCinder bamisCinder = new BamisCinder();
    public static BandleglassMirror bandleglassMirror = new BandleglassMirror();
    public static BansheesVeil bansheesVeil = new BansheesVeil();
    public static BerserkersGreaves berserkersGreaves = new BerserkersGreaves();
    public static BFSword bFSword = new BFSword();
    public static BlackCleaver blackCleaver = new BlackCleaver();
    public static BlackfireTorch blackfireTorch = new BlackfireTorch(1);
    public static BladeOfTheRuinedKing bladeOfTheRuinedKing = new BladeOfTheRuinedKing();
    public static BlastingWand blastingWand = new BlastingWand();
    public static BlightingJewel blightingJewel = new BlightingJewel();
    public static BloodlettersCurse bloodlettersCurse = new BloodlettersCurse();
    public static Bloodsong bloodsong = new Bloodsong();
    public static Bloodthirster bloodthirster = new Bloodthirster();
    public static Boots boots = new Boots();
    public static BootsOfSwiftness bootsOfSwiftness = new BootsOfSwiftness();
    public static BountyOfWorlds bountyOfWorlds = new BountyOfWorlds();
    public static BrambleVest brambleVest = new BrambleVest();
    public static CatalystOfAeons catalystOfAeons = new CatalystOfAeons();
    public static CaulfieldsWarhammer caulfieldsWarhammer = new CaulfieldsWarhammer();
    public static CelestialOpposition celestialOpposition = new CelestialOpposition();
    public static ChainVest chainVest = new ChainVest();
    public static ChempunkChainsword chempunkChainsword = new ChempunkChainsword();
    public static CloakOfAgility cloakOfAgility = new CloakOfAgility();
    public static ClothArmor clothArmor = new ClothArmor();
    public static CosmicDrive cosmicDrive = new CosmicDrive();
    public static Cryptbloom cryptbloom = new Cryptbloom();
    public static CrystallineBracer crystallineBracer = new CrystallineBracer();
    public static Cull cull = new Cull();
    public static Dagger dagger = new Dagger();
    public static DarkSeal darkSeal = new DarkSeal(0);
    public static Dawncore dawncore = new Dawncore();
    public static DeadMansPlate deadMansPlate = new DeadMansPlate();
    public static DeathsDance deathsDance = new DeathsDance();
    public static DoransBlade doransBlade = new DoransBlade();
    public static DoransRing doransRing = new DoransRing();
    public static DoransShield doransShield = new DoransShield();
    public static DreamMaker dreamMaker = new DreamMaker();
    public static EchoesOfHelia echoesOfHelia = new EchoesOfHelia();
    public static Eclipse eclipse = new Eclipse();
    public static EdgeOfNight edgeOfNight = new EdgeOfNight();
    public static EssenceReaver essenceReaver = new EssenceReaver();
    public static ExecutionersCalling executionersCalling = new ExecutionersCalling();
    public static ExperimentalHexplate experimentalHexplate = new ExperimentalHexplate();
    public static FaerieCharm faerieCharm = new FaerieCharm();
    public static FatedAshes fatedAshes = new FatedAshes();
    public static FiendishCodex fiendishCodex = new FiendishCodex();
    public static Fimbulwinter fimbulwinter = new Fimbulwinter();
    public static ForbiddenIdol forbiddenIdol = new ForbiddenIdol();
    public static ForceOfNature forceOfNature = new ForceOfNature();
    public static FrozenHeart frozenHeart = new FrozenHeart();
    public static GiantsBelt giantsBelt = new GiantsBelt();
    public static GlacialBuckler glacialBuckler = new GlacialBuckler();
    public static GlowingMote glowingMote = new GlowingMote();
    public static GuardianAngel guardianAngel = new GuardianAngel();
    public static GuardiansBlade guardiansBlade = new GuardiansBlade();
    public static GuardiansHammer guardiansHammer = new GuardiansHammer();
    public static GuardiansHorn guardiansHorn = new GuardiansHorn();
    public static GuardiansOrb guardiansOrb = new GuardiansOrb();
    public static GuinsoosRageblade guinsoosRageblade = new GuinsoosRageblade();
    public static HauntingGuise hauntingGuise = new HauntingGuise();
    public static HearthboundAxe hearthboundAxe = new HearthboundAxe();
    public static Heartsteel heartsteel = new Heartsteel();
    public static Hexdrinker hexdrinker = new Hexdrinker();
    public static HextechAlternator hextechAlternator = new HextechAlternator();
    public static HextechRocketbelt hextechRocketbelt = new HextechRocketbelt();
    public static HollowRadiance hollowRadiance = new HollowRadiance();
    public static HorizonFocus horizonFocus = new HorizonFocus();
    public static Hubris hubris = new Hubris();
    public static Hullbreaker hullbreaker = new Hullbreaker();
    public static IcebornGauntlet icebornGauntlet = new IcebornGauntlet();
    public static ImmortalShieldbow immortalShieldbow = new ImmortalShieldbow();
    public static ImperialMandate imperialMandate = new ImperialMandate();
    public static InfinityEdge infinityEdge = new InfinityEdge();
    public static IonianBootsOfLucidity ionianBootsOfLucidity = new IonianBootsOfLucidity();
    public static JakSho jakSho = new JakSho();
    public static KaenicRookern kaenicRookern = new KaenicRookern();
    public static Kindlegem kindlegem = new Kindlegem();
    public static KnightsVow knightsVow = new KnightsVow();
    public static KrakenSlayer krakenSlayer = new KrakenSlayer();
    public static LastWhisper lastWhisper = new LastWhisper();
    public static LiandrysTorment liandrysTorment = new LiandrysTorment();
    public static LichBane lichBane = new LichBane();
    public static LocketOfTheIronSolari locketOfTheIronSolari = new LocketOfTheIronSolari();
    public static LongSword longSword = new LongSword();
    public static LordDominiksRegards lordDominiksRegards = new LordDominiksRegards();
    public static LostChapter lostChapter = new LostChapter();
    public static LudensCompanion ludensCompanion = new LudensCompanion();
    public static Malignance malignance = new Malignance();
    public static Manamune manamune = new Manamune(0);
    public static MawOfMalmortius mawOfMalmortius = new MawOfMalmortius();
    public static MejaisSoulstealer mejaisSoulstealer = new MejaisSoulstealer(0);
    public static MercurialScimitar mercurialScimitar = new MercurialScimitar();
    public static MercurysTreads mercurysTreads = new MercurysTreads();
    public static MikaelsBlessing mikaelsBlessing = new MikaelsBlessing();
    public static MoonstoneRenewer moonstoneRenewer = new MoonstoneRenewer();
    public static Morellonomicon morellonomicon = new Morellonomicon();
    public static MortalReminder mortalReminder = new MortalReminder();
    public static Muramana muramana = new Muramana();
    public static NashorsTooth nashorsTooth = new NashorsTooth();
    public static NavoriFlickerblade navoriQuickblades = new NavoriFlickerblade();
    public static NeedlesslyLargeRod needlesslyLargeRod = new NeedlesslyLargeRod();
    public static NegatronCloak negatronCloak = new NegatronCloak();
    public static Noonquiver noonquiver = new Noonquiver();
    public static NullMagicMantle nullMagicMantle = new NullMagicMantle();
    public static OblivionOrb oblivionOrb = new OblivionOrb();
    public static Opportunity opportunity = new Opportunity();
    public static OverlordsBloodmail overlordsBloodmail = new OverlordsBloodmail();
    public static Phage phage = new Phage();
    public static PhantomDancer phantomDancer = new PhantomDancer();
    public static Pickaxe pickaxe = new Pickaxe();
    public static PlatedSteelcaps platedSteelcaps = new PlatedSteelcaps();
    public static ProfaneHydra profaneHydra = new ProfaneHydra();
    public static QuicksilverSash quicksilverSash = new QuicksilverSash();
    public static RabadonsDeathcap rabadonsDeathcap = new RabadonsDeathcap();
    public static RanduinsOmen randuinsOmen = new RanduinsOmen();
    public static RapidFirecannon rapidFirecannon = new RapidFirecannon();
    public static RavenousHydra ravenousHydra = new RavenousHydra();
    public static Rectrix rectrix = new Rectrix();
    public static RecurveBow recurveBow = new RecurveBow();
    public static Redemption redemption = new Redemption();
    public static RejuvenationBead rejuvenationBead = new RejuvenationBead();
    public static Riftmaker riftmaker = new Riftmaker();
    public static RodOfAges rodOfAges = new RodOfAges(10);
    public static RubyCrystal rubyCrystal = new RubyCrystal();
    public static RunaansHurricane runaansHurricane = new RunaansHurricane();
    public static RunicCompass runicCompass = new RunicCompass();
    public static RylaisCrystalScepter rylaisCrystalScepter = new RylaisCrystalScepter();
    public static SapphireCrystal sapphireCrystal = new SapphireCrystal();
    public static ScoutsSlingshot scoutsSlingshot = new ScoutsSlingshot();
    public static SeekersArmguard seekersArmguard = new SeekersArmguard();
    public static SeraphsEmbrace seraphsEmbrace = new SeraphsEmbrace();
    public static SerpentsFang serpentsFang = new SerpentsFang();
    public static SerratedDirk serratedDirk = new SerratedDirk();
    public static SeryldasGrudge seryldasGrudge = new SeryldasGrudge();
    public static Shadowflame shadowflame = new Shadowflame();
    public static Sheen sheen = new Sheen();
    public static ShurelyasBattlesong shurelyasBattlesong = new ShurelyasBattlesong();
    public static SolsticeSleigh solsticeSleigh = new SolsticeSleigh();
    public static SorcerersShoes sorcerersShoes = new SorcerersShoes();
    public static SpearOfShojin spearOfShojin = new SpearOfShojin();
    public static SpectresCowl spectresCowl = new SpectresCowl();
    public static SpiritVisage spiritVisage = new SpiritVisage();
    public static StaffOfFlowingWater staffOfFlowingWater = new StaffOfFlowingWater();
    public static StatikkShiv statikkShiv = new StatikkShiv();
    public static SteelSigil steelSigil = new SteelSigil();
    public static SteraksGage steraksGage = new SteraksGage();
    public static Stormsurge stormsurge = new Stormsurge();
    public static Stridebreaker stridebreaker = new Stridebreaker();
    public static SunderedSky sunderedSky = new SunderedSky();
    public static SunfireAegis sunfireAegis = new SunfireAegis();
    public static SymbioticSoles symbioticSoles = new SymbioticSoles();
    public static SynchronizedSouls synchronizedSouls = new SynchronizedSouls();
    public static TearOfTheGoddess tearOfTheGoddess = new TearOfTheGoddess(0);
    public static Terminus terminus = new Terminus();
    public static TheBrutalizer theBrutalizer = new TheBrutalizer();
    public static TheCollector theCollector = new TheCollector();
    public static Thornmail thornmail = new Thornmail();
    public static Tiamat tiamat = new Tiamat();
    public static TitanicHydra titanicHydra = new TitanicHydra();
    public static Trailblazer trailblazer = new Trailblazer();
    public static TrinityForce trinityForce = new TrinityForce();
    public static Tunneler tunneler = new Tunneler();
    public static UmbralGlaive umbralGlaive = new UmbralGlaive();
    public static UnendingDespair unendingDespair = new UnendingDespair();
    public static VampiricScepter vampiricScepter = new VampiricScepter();
    public static VerdantBarrier verdantBarrier = new VerdantBarrier();
    public static VigilantWardstone vigilantWardstone = new VigilantWardstone();
    public static VoidStaff voidStaff = new VoidStaff();
    public static VoltaicCyclosword voltaicCyclosword = new VoltaicCyclosword();
    public static WardensMail wardensMail = new WardensMail();
    public static WarmogsArmor warmogsArmor = new WarmogsArmor();
    public static WatchfulWardstone watchfulWardstone = new WatchfulWardstone();
    public static WingedMoonplate wingedMoonplate = new WingedMoonplate();
    public static WintersApproach wintersApproach = new WintersApproach(0);
    public static WitsEnd witsEnd = new WitsEnd();
    public static WorldAtlas worldAtlas = new WorldAtlas();
    public static YoumuusGhostblade youmuusGhostblade = new YoumuusGhostblade();
    public static YunTalWildarrows yunTalWildarrows = new YunTalWildarrows(0);
    public static ZazZaksRealmspike zazZaksRealmspike = new ZazZaksRealmspike();
    public static Zeal zeal = new Zeal();
    public static ZekesConvergence zekesConvergence = new ZekesConvergence();
    public static ZhonyasHourglass zhonyasHourglass = new ZhonyasHourglass();


    public static ArrayList<Item> allItems = new ArrayList<>() {{
        add(abyssalMask);
        add(aegisOfTheLegion);
        add(aetherWisp);
        add(amplifyingTome);
        add(archangelsStaff);
        add(ardentCenser);
        add(axiomArc);
        add(bamisCinder);
        add(bandleglassMirror);
        add(bansheesVeil);
        add(berserkersGreaves);
        add(bFSword);
        add(blackCleaver);
        add(blackfireTorch);
        add(bladeOfTheRuinedKing);
        add(blastingWand);
        add(blightingJewel);
        add(bloodlettersCurse);
        add(bloodsong);
        add(bloodthirster);
        add(boots);
        add(bootsOfSwiftness);
        add(bountyOfWorlds);
        add(brambleVest);
        add(catalystOfAeons);
        add(caulfieldsWarhammer);
        add(celestialOpposition);
        add(chainVest);
        add(chempunkChainsword);
        add(cloakOfAgility);
        add(clothArmor);
        add(cosmicDrive);
        add(cryptbloom);
        add(crystallineBracer);
        add(cull);
        add(dagger);
        add(darkSeal);
        add(dawncore);
        add(deadMansPlate);
        add(deathsDance);
        add(doransBlade);
        add(doransRing);
        add(doransShield);
        add(dreamMaker);
        add(echoesOfHelia);
        add(eclipse);
        add(edgeOfNight);
        add(essenceReaver);
        add(executionersCalling);
        add(experimentalHexplate);
        add(faerieCharm);
        add(fatedAshes);
        add(fiendishCodex);
        add(fimbulwinter);
        add(forbiddenIdol);
        add(forceOfNature);
        add(frozenHeart);
        add(giantsBelt);
        add(glacialBuckler);
        add(glowingMote);
        add(guardianAngel);
        add(guardiansBlade);
        add(guardiansHammer);
        add(guardiansHorn);
        add(guardiansOrb);
        add(guinsoosRageblade);
        add(hauntingGuise);
        add(hearthboundAxe);
        add(heartsteel);
        add(hexdrinker);
        add(hextechAlternator);
        add(hextechRocketbelt);
        add(hollowRadiance);
        add(horizonFocus);
        add(hubris);
        add(hullbreaker);
        add(icebornGauntlet);
        add(immortalShieldbow);
        add(imperialMandate);
        add(infinityEdge);
        add(ionianBootsOfLucidity);
        add(jakSho);
        add(kaenicRookern);
        add(kindlegem);
        add(knightsVow);
        add(krakenSlayer);
        add(lastWhisper);
        add(liandrysTorment);
        add(lichBane);
        add(locketOfTheIronSolari);
        add(longSword);
        add(lordDominiksRegards);
        add(lostChapter);
        add(ludensCompanion);
        add(malignance);
        add(manamune);
        add(mawOfMalmortius);
        add(mejaisSoulstealer);
        add(mercurialScimitar);
        add(mercurysTreads);
        add(mikaelsBlessing);
        add(moonstoneRenewer);
        add(morellonomicon);
        add(mortalReminder);
        add(muramana);
        add(nashorsTooth);
        add(navoriQuickblades);
        add(needlesslyLargeRod);
        add(negatronCloak);
        add(noonquiver);
        add(nullMagicMantle);
        add(oblivionOrb);
        add(opportunity);
        add(overlordsBloodmail);
        add(phage);
        add(phantomDancer);
        add(pickaxe);
        add(platedSteelcaps);
        add(profaneHydra);
        add(quicksilverSash);
        add(rabadonsDeathcap);
        add(randuinsOmen);
        add(rapidFirecannon);
        add(ravenousHydra);
        add(rectrix);
        add(recurveBow);
        add(redemption);
        add(rejuvenationBead);
        add(riftmaker);
        add(rodOfAges);
        add(rubyCrystal);
        add(runaansHurricane);
        add(runicCompass);
        add(rylaisCrystalScepter);
        add(sapphireCrystal);
        add(scoutsSlingshot);
        add(seekersArmguard);
        add(seraphsEmbrace);
        add(serpentsFang);
        add(serratedDirk);
        add(seryldasGrudge);
        add(shadowflame);
        add(sheen);
        add(shurelyasBattlesong);
        add(solsticeSleigh);
        add(sorcerersShoes);
        add(spearOfShojin);
        add(spectresCowl);
        add(spiritVisage);
        add(staffOfFlowingWater);
        add(statikkShiv);
        add(steelSigil);
        add(steraksGage);
        add(stormsurge);
        add(stridebreaker);
        add(sunderedSky);
        add(sunfireAegis);
        add(symbioticSoles);
        add(synchronizedSouls);
        add(tearOfTheGoddess);
        add(terminus);
        add(theBrutalizer);
        add(theCollector);
        add(thornmail);
        add(tiamat);
        add(titanicHydra);
        add(trailblazer);
        add(trinityForce);
        add(tunneler);
        add(umbralGlaive);
        add(unendingDespair);
        add(vampiricScepter);
        add(verdantBarrier);
        add(vigilantWardstone);
        add(voidStaff);
        add(voltaicCyclosword);
        add(wardensMail);
        add(warmogsArmor);
        add(watchfulWardstone);
        add(wingedMoonplate);
        add(wintersApproach);
        add(witsEnd);
        add(worldAtlas);
        add(youmuusGhostblade);
        add(yunTalWildarrows);
        add(zazZaksRealmspike);
        add(zeal);
        add(zekesConvergence);
        add(zhonyasHourglass);
    }};
    public static HashMap<String, Item> nameToItem = new HashMap<>();
    static {
        for (Item i : allItems) nameToItem.put(i.name, i);
    }
}
